---
- name: url checking uc
  hosts: localhost
  become: true
  ignore_errors: true
  tasks:
    
    - name: creating csv file
      delegate_to: localhost
      become: true
      shell: |
        echo "https://www.dr.eye2serve.com:9001/sap/bc/ui5_ui5/sap/zdca_portal?saml2=disabled" > /tmp/url_links.csv
        echo "https://utcloud.eye2serve.com/utclstorefront/utcl/en/login"  >> /tmp/url_links.csv
        echo "https://wddr.eye2serve.com:50000/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html" >> /tmp/url_links.csv
        echo "https://www.dr.eye2serve.com:9001/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html" >> /tmp/url_links.csv
        echo "https://www.eye2serve.com:9001/sap/bc/ui5_ui5/sap/zdca_portal?saml2=disabled" >> /tmp/url_links.csv
        echo "https://utcloud.eye2serve.com/utclstorefront/utcl/en/login" >> /tmp/url_links.csv
        echo "https://wdpr.eye2serve.com:50000/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html" >> /tmp/url_links.csv
        echo "https://www.eye2serve.com:9001/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html" >> /tmp/url_links.csv
        echo "https://ucp.utclconnect.com/irj/portal?saml2=disabled" >> /tmp/url_links.csv
        echo "https://ucp.dr.utclconnect.com/irj/portal?saml2=disabled" >> /tmp/url_links.csv
  
  # echo "https://www.dr.eye2serve.com:9001/sap/bc/ui5_ui5/sap/zdca_portal?saml2=disabled" > /tmp/url_links.csv
  # echo "https://utcloud.eye2serve.com/utclstorefront/utcl/en/login"  >> /tmp/url_links.csv
  # echo "https://www.dr.eye2serve.com:9001/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html" >> /tmp/url_links.csv
  # echo "https://www.eye2serve.com:9001/sap/bc/ui5_ui5/sap/zdca_portal?saml2=disabled" >> /tmp/url_links.csv
  # echo "https://utcloud.eye2serve.com/utclstorefront/utcl/en/login" >> /tmp/url_links.csv
  # echo "https://www.eye2serve.com:9001/sap/bc/ui5_ui5/ui2/ushell/shells/abap/FioriLaunchpad.html" >> /tmp/url_links.csv
  # echo "https://ucp.utclconnect.com/irj/portal?saml2=disabled" >> /tmp/url_links.csv
  # echo "https://ucp.dr.utclconnect.com/irj/portal?saml2=disabled" >> /tmp/url_links.csv
  
    - name: creating csv file
      delegate_to: localhost
      become: true
      shell: | 
          cat /tmp/url_links.csv
      register: csv_file_data

    - set_fact:
        url_list: "{{ csv_file_data.stdout_lines }}"

    - set_fact:
        hostname: '{{ hostname | default([]) + [item | urlsplit("hostname")] }}'
      loop: "{{ csv_file_data.stdout_lines }}"

    # - debug: var=hostname

    - set_fact:
        port_num: "{{ port_num | default([]) + [item | urlsplit('port') | default(443) if (item | urlsplit('port')) is not none else 443] }}"
      loop: "{{ csv_file_data.stdout_lines }}"
      
    # - debug: var=port_num

    - name: Calculate expiry date two months from now
      set_fact:
        current_date: "{{ ansible_date_time.date | regex_replace('-', '') }}"

    # - name: Calculate expiry date two months from now
    #   shell: date -d "{{ current_date }} +2 months" +%Y%m%d
    #   register: two_months_date_result

    - name: check the exipiry date of url of Secondary Operation Automation
      get_certificate:
        host: "{{ item.0 }}"
        port: "{{ item.1 | int }}"          
      delegate_to: localhost
      run_once: true
      register: secon_operation_automation_1
      with_together:
        - "{{ hostname }}"
        - "{{ port_num }}"
    
    - name: set fact for the CN of the url of Secondary Operation Automation 
      set_fact:
        all_cn_names: "{{ all_cn_names | default([]) + [item.subject.CN] | list }}"
      with_items: "{{ secon_operation_automation_1.results }}"
    
    # - debug: var=all_cn_names
    
    - name: task for formatted expirydate
      shell: |
        date -d "$(echo '{{ item.not_after}}' | cut -c 1-8)" "+%A, %B %d, %Y"
      register: formatted_date_1
      with_items: "{{ secon_operation_automation_1.results }}"

    - name: set fact task for raw expirydate from not_after parameter
      set_fact:
        raw_expirydate: "{{ raw_expirydate | default([]) + [item.not_after] | list }}"
      with_items: "{{ secon_operation_automation_1.results }}"

#     - debug: var=formatted_date_1
#     - debug: 
#         msg: "{{ item.stdout_lines }}"
#       with_items: "{{ formatted_date_1.results }}"
      
    - name: set fact for the formatted dates
      set_fact:
        formatted_date_set_fact: "{{ formatted_date_set_fact | default([]) + item.stdout_lines }}"
      with_items: "{{ formatted_date_1.results }}"
      
    - debug: var=formatted_date_set_fact
    
    - name: set fact for the expiry date without formatted
      set_fact:
        without_formatted_date_set_fact: "{{ item.not_after | regex_replace('(\\d{4})(\\d{2})(\\d{2}).*', '\\1\\2\\3') }}"
      register: without_formatted_date
      with_items: "{{ secon_operation_automation_1.results }}"
      
    # - debug: var=without_formatted_date
    
    # - debug:
    #     msg: "{{ item.ansible_facts.without_formatted_date_set_fact }}"
    #   with_items: "{{ without_formatted_date.results }}"

    - name: set fact for the without formatted dates
      set_fact:
        without_formatted_set_fact: "{{ without_formatted_set_fact | default([]) + [item.ansible_facts.without_formatted_date_set_fact] |list }}"
      with_items: "{{ without_formatted_date.results }}"
      
    # - debug: var=without_formatted_set_fact
    
    - name: setfacts for all common names and expiry days
      set_fact:
        expiry_date_difference_days : "{{ (item | to_datetime('%Y%m%d')) - (current_date | to_datetime('%Y%m%d')) }}"
      with_items: "{{ without_formatted_set_fact }}"
      register: difference_days_reg
   
    # - debug: var=expiry_date_difference_days
    # - debug: var=difference_days_reg
    
    - name: setfacts for all expiry formated days
      set_fact:
        formatted_expiry_date_difference_days :  "{{ formatted_expiry_date_difference_days  | default([]) + [item.ansible_facts.expiry_date_difference_days.split(' ')[0]] }}"
      with_items: "{{ difference_days_reg.results }}"
    
    # - debug: var=formatted_expiry_date_difference_days

    - name: set Headers
      shell: echo "Application_URLs,Expiry_Date,Common_name,Expire_in_days,Raw_expiry_date" > /var/consolidated_url_expiry.csv
      run_once: true
      become: true
      delegate_to: localhost


    - name: Append the data of DBS
      throttle: 1
      become: true
      shell: echo "{{ item.0  }}, {{ item.1 }}, {{ item.2 }}, {{ item.3 }}, {{ item.4 }}" >> /var/consolidated_url_expiry.csv
      delegate_to: localhost
      with_together:
      - "{{ url_list }}"
      - "{{ without_formatted_set_fact }}"
      - "{{ all_cn_names }}"
      - "{{ formatted_expiry_date_difference_days }}"
      - "{{ raw_expirydate }}"

#####################################################

    - name: fiften_days date from "{{ current_date }}"
      shell: date -d "{{ current_date }} +15 days" +%Y%m%d
      register: fifteen_days_date_result

    - name: calling read csv module
      become: true
      read_csv: 
        path: /var/consolidated_url_expiry.csv
      register: consolidated_csv_data

    - set_fact: 
        consolidated_csv_url_links_list: "{{ consolidated_csv_data.list | map(attribute=columnname) | list}}"
      vars:
        - columnname: 'Application_URLs'

    - debug: var=consolidated_csv_url_links_list

    - set_fact: 
        consolidated_csv_unformatted_expiry_date_list: "{{ consolidated_csv_data.list | map(attribute=columnname) | map('trim')  | list}}"
      vars:
        - columnname: 'Expiry_Date'
        
    - debug: var=consolidated_csv_unformatted_expiry_date_list

    - set_fact: 
        consolidated_csv_common_name_list: "{{ consolidated_csv_data.list | map(attribute=columnname) | map('trim') | list}}"
      vars:
        - columnname: 'Common_name'
        
    - debug: var=consolidated_csv_common_name_list

    - set_fact: 
        consolidated_csv_expiry_days_list: "{{ consolidated_csv_data.list | map(attribute=columnname) | map('trim') | list}}"
      vars:
        - columnname: 'Expire_in_days'
        
    - debug: var=consolidated_csv_expiry_days_list

    - set_fact: 
        consolidated_csv_raw_expiry_date_list: "{{ consolidated_csv_data.list | map(attribute=columnname)  | map('trim') | list}}"
      vars:
        - columnname: 'Raw_expiry_date'
        
    - debug: var=consolidated_csv_raw_expiry_date_list


    - name: task for raw formatted expirydate
      shell: |
        date -d "$(echo '{{ item }}' | cut -c 1-8)" "+%A, %B %d, %Y"
      register: raw_formatted_date
      with_items: "{{ consolidated_csv_raw_expiry_date_list }}"

    - name: set fact for the raw formatted dates
      set_fact:
        raw_formatted_date_set_fact: "{{ raw_formatted_date_set_fact | default([]) + item.stdout_lines }}"
      with_items: "{{ raw_formatted_date.results }}"
      
    - debug: var=raw_formatted_date_set_fact

    # - name: set fact for the raw formatted dates
    #   set_fact:
    #     consolidated_csv_unformatted_expiry_date_list_1: ["20240815","20230206","20240815","20230206","20250206","20250206","20240620","20241215"]

    - name: Sending an email using Ansible
      mail:
        # host: "smtp.sendgrid.net"
        # port: "465"
        # username: "apikey"
        # password: "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"
        # from: "Ansible Bot <eca.ansible@ibm.com>"
        # to: "Bathula.Chandra.Sekhar@ibm.com"
        # cc: "Bathula.Chandra.Sekhar@ibm.com"

        host: "{{ email_host }}"
        port: "{{ email_port_num }}"
        from: "Ultra Tech Bot<ansiblebot@adityabirla.com>"
        to: "{{ to_mail }}"
        cc: "{{ cc_mail }}"

        subject: "Url Certificate Expiry Alert - IMMEDIATE ACTION NEEDED for {{ item.0 }}"
        body: |
          Greetings,<br>
          The certificate for URL {{ item.1 }} is about to expire within 15 days.<br><br>
          Certificate expiry date: {{ item.2 }}<br>
          CN: {{ item.0 }}<br><br>
          Regards,<br>
          Ultra Tech Bot
        subtype: html
      delegate_to: localhost
      with_together:
        - "{{ consolidated_csv_common_name_list }}"
        - "{{ consolidated_csv_url_links_list }}"
        - "{{ raw_formatted_date_set_fact }}"
        - "{{ consolidated_csv_unformatted_expiry_date_list }}"
      when: "{{ item.3 | int < fifteen_days_date_result.stdout | int }}"



